# Generated by Django 3.2.9 on 2022-01-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20220125_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('electronics', 'Electronics'), ('laptops', 'Laptop'), ('cloth', 'Cloth'), ('house_utensils', 'House Utensil'), ('book', 'Book'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending')], default='pending', max_length=15),
        ),
    ]
